mode: daemonset
resources:
  limits:
    cpu: 1
    memory: 1Gi
image:
  tag: "0.84.0"
presets:
  kubernetesAttributes:
    enabled: true
extraEnvs:
  - name: HONEYCOMB_API_KEY
    valueFrom:
      secretKeyRef:
        name: honeycomb-api-key
        key: api-key
config:
  exporters:
    otlp:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}

    otlp/metrics:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-metrics

    otlp/logging:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-logs

  service:
    telemetry:
      logs:
        level: "debug"
    pipelines:
      traces:
        exporters: [otlp]
      metrics:
        exporters: [otlp/metrics]
      logs:
        exporters: [otlp/logging]
