apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: busybox
      resources: {}
      env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  dnsPolicy: ClusterFirst
  restartPolicy: Never
