apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
    image: busybox
    name: busybox
    resources: {}
    - args:
        - sleep
        - "3600"
    env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
        fieldPath: status.hostIP
  dnsPolicy: ClusterFirst
  restartPolicy: Never
