# Helm release: daemonset-opentelemetry-collector
# Helm chart: open-telemetry/opentelemetry-collector
mode: daemonset
resources:
  limits:
    cpu: "0.5"
    memory: 400Mi
image:
  tag: "0.102.1"
  repository: "otel/opentelemetry-collector-contrib"
presets:
  kubernetesAttributes:
    enabled: true
  kubeletMetrics:
    enabled: true
  logsCollection:
    enabled: true
extraEnvs:
  - name: HONEYCOMB_API_KEY
    valueFrom:
      secretKeyRef:
        name: honeycomb-api-key
        key: api-key
  - name: NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: HONEYCOMB_O11YDAY_API_KEY
    valueFrom:
      secretKeyRef:
        name: honeycomb-o11yday-api-key
        key: api-key
ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: false
config:
  processors:
    filter/only-o11yday-namespace:
      error_mode: ignore
      logs:
        log_record:
          - resource.attributes["k8s.namespace.name"] != "o11yday"
      metrics:
        metric:
          - resource.attributes["k8s.namespace.name"] != "o11yday"
    transform/kubeletstats:
      metric_statements:
        - context: resource
          statements:
            - set(attributes["meta.signal_type"], "metrics") where attributes["meta.signal_type"] == nil
            - set(attributes["collector.receiver"], "kubeletstats")
            - set(attributes["collector.collector"], "daemonset-demo-k8s") where attributes["collector.collector"] == nil
            - set(attributes["collector.pipeline"], "metrics/kubeletstats") where attributes["collector.pipeline"] == nil
    transform/kubeletstats-o11yday:
      metric_statements:
        - context: resource
          statements:
            - set(attributes["meta.signal_type"], "metrics") where attributes["meta.signal_type"] == nil
            - set(attributes["collector.collector"], "daemonset-demo-k8s") where attributes["collector.collector"] == nil
            - set(attributes["collector.receiver"], "kubeletstats")
            - set(attributes["collector.pipeline"], "metrics/kubeletstats-o11yday") where attributes["collector.pipeline"] == nil
    transform/metrics-other:
      metric_statements:
        - context: resource
          statements:
            - set(attributes["meta.signal_type"], "metrics") where attributes["meta.signal_type"] == nil
            - set(attributes["collector.collector"], "daemonset-demo-k8s") where attributes["collector.collector"] == nil
            - set(attributes["collector.receiver"], "prometheus, otlp")
            - set(attributes["collector.pipeline"], "metrics") where attributes["collector.pipeline"] == nil
    transform/other:
      metric_statements:
        - context: resource
          statements:
            - set(attributes["meta.signal_type"], "metrics") where attributes["meta.signal_type"] == nil
            - set(attributes["collector.collector"], "daemonset-demo-k8s") where attributes["collector.collector"] == nil
      trace_statements:
        - context: resource
          statements:
            - set(attributes["collector.collector"], "daemonset-demo-k8s") where attributes["collector.collector"] == nil
      log_statements:
        - context: resource
          statements:
            - set(attributes["collector.collector"], "daemonset-demo-k8s") where attributes["collector.collector"] == nil
  receivers:
    jaeger: null
    zipkin: null
    kubeletstats:
      endpoint: "https://${NODE_IP}:10250"
      insecure_skip_verify: true
  exporters:
    otlp/jaeger:
      endpoint: "otel-demo-jaeger-collector:4317"
      tls:
        insecure: true
    otlp:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
    otlp/metrics:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: all-the-metrics
    otlp/metrics-o11yday:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_O11YDAY_API_KEY}
        x-honeycomb-dataset: k8s-metrics

    otlp/logging:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: all-the-logs

    otlp/hny-o11yday:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_O11YDAY_API_KEY}
        x-honeycomb-dataset: scraped-logs
    opensearch:
      http:
        endpoint: http://otel-demo-opensearch:9200
        tls:
          insecure: true
      logs_index: otel
    opensearch/o11yday:
      dataset: logs
      namespace: o11y-day
      http:
        endpoint: http://otel-demo-opensearch:9200
        tls:
          insecure: true
      logs_index: o11yday

  service:
    telemetry:
      logs:
        level: "info"
    pipelines:
      traces:
        receivers: [otlp]
        processors: [k8sattributes, transform/other, memory_limiter, batch]
        exporters: [otlp]
      metrics:
        receivers: [prometheus, otlp]
        processors:
          [k8sattributes, transform/metrics-other, memory_limiter, batch]
        exporters: [otlp/metrics]
      metrics/kubeletstats:
        receivers: [kubeletstats]
        processors:
          [k8sattributes, transform/kubeletstats, memory_limiter, batch]
        exporters: [otlp/metrics]
      metrics/kubeletstats-o11yday:
        receivers: [kubeletstats]
        processors:
          [
            k8sattributes,
            filter/only-o11yday-namespace,
            transform/kubeletstats-o11yday,
            memory_limiter,
            batch,
          ]
        exporters: [otlp/metrics-o11yday]
      logs:
        receivers: [otlp, filelog]
        processors: [k8sattributes, transform/other, memory_limiter, batch]
        exporters: [otlp/logging, opensearch]
      traces/o11yday:
        receivers: [otlp]
        processors:
          [
            k8sattributes,
            filter/only-o11yday-namespace,
            transform/other,
            memory_limiter,
            batch,
          ]
        exporters: [otlp/hny-o11yday, otlp/jaeger]
      logs/o11yday:
        receivers: [filelog]
        processors:
          [
            k8sattributes,
            filter/only-o11yday-namespace,
            transform/other,
            memory_limiter,
            batch,
          ]
        exporters: [otlp/hny-o11yday, opensearch/o11yday]
