apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8vIjp7InVzZXJuYW1lIjoiamVzc2l0cm9uIiwicGFzc3dvcmQiOiJnaHBfbDZMcFdlcUVHTkRybmx4c3BmcmlDUGdDb3YwTWsxMEh5M3NoIiwiYXV0aCI6ImFtVnpjMmwwY205dU9tZG9jRjlzTmt4d1YyVnhSVWRPUkhKdWJIaHpjR1p5YVVOUVowTnZkakJOYXpFd1NIa3pjMmc9In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
