components:
  frontendProxy:
    ingress:
      # Enable the creation of Ingress rules. Default is false
      enabled: true
      # Annotations to add to the ingress rule
      annotations: {}
      # Which Ingress class (controller) to use. Default is unspecified.
      ingressClassName: alb
      # Hosts definitions for the Ingress rule
      hosts:
        - host: otel-demo.jessitron.com
          # Each host can have multiple paths/routes
          paths:
            - path: /
              pathType: Prefix
              port: 8080
