components:
  frontend:
    env:
      - name: NEXT_PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: "http://k8s-oteldemo-22aaaf0b73-1367568571.us-west-2.elb.amazonaws.com"
      - name: NEXT_PUBLIC_OTEL_SERVICE_NAME
        value: "frontend-client"
