components:
  frontendProxy:
    enabled: true
    ingress:
      # Enable the creation of Ingress rules. Default is false
      enabled: true
      # Annotations to add to the ingress rule
      annotations:
        {
          alb.ingress.kubernetes.io/group.name: "otel-demo",
          alb.ingress.kubernetes.io/target-type: "ip",
          alb.ingress.kubernetes.io/scheme: "internet-facing",
        }
      # Which Ingress class (controller) to use. Default is unspecified.
      ingressClassName: alb
      # Hosts definitions for the Ingress rule
      hosts:
        - host: "k8s-oteldemo-22aaaf0b73-1367568571.us-west-2.elb.amazonaws.com"
          # Each host can have multiple paths/routes
          paths:
            - path: /
              pathType: Prefix
              port: 8080
