components:
  frontend:
    enabled: true
    envOverrides:
      - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: "/v1/traces"

opentelemetry-collector:
  image:
    tag: "0.75.0"
  presets:
    kubernetesAttributes:
      enabled: true
    clusterMetrics:
      enabled: true
    kubernetesEvents:
      enabled: true
  config:
    receivers:
      otlp:
        protocols:
          http:
            cors:
              allowed_origins:
                - http://k8s-oteldemo-497054d7c2-763859031.us-west-2.elb.amazonaws.com
            endpoint: ${MY_POD_IP}:4318
    exporters:
      otlp/honeycomb:
        endpoint: "api.honeycomb.io:443"
        headers:
          "x-honeycomb-dataset": all-the-metrics
          "x-honeycomb-team": "FecmbNqfOaYqsELVH54OrD"

    service:
      pipelines:
        traces:
          processors: [memory_limiter, batch]
          exporters: [otlp, logging, otlp/honeycomb, spanmetrics]
        metrics:
          exporters: [otlp/honeycomb]
