# Helm release: service-opentelemetry-collector
# Helm chart: open-telemetry/opentelemetry-collector
mode: deployment
resources:
  limits:
    cpu: 1
    memory: 1Gi
image:
  tag: "0.84.0"
presets:
  kubernetesAttributes:
    enabled: true
extraEnvs:
  - name: HONEYCOMB_API_KEY
    valueFrom:
      secretKeyRef:
        name: honeycomb-api-key
        key: api-key
ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: false
config:
  processors:
    transform/labelme:
      metric_statements:
        - context: resource
          statements:
            - set(attributes["meta.signal_type"], "metrics") where attributes["meta.signal_type"] == nil
            - set(attributes["collector.collector"], "service-opentelemetry-collector")
      trace_statements:
        - context: resource
          statements:
            - set(attributes["collector.collector"], "service-opentelemetry-collector")
      log_statements:
        - context: resource
          statements:
            - set(attributes["collector.collector"], "service-opentelemetry-collector")
  receivers:
    jaeger: null
    zipkin: null
    prometheus: null
  exporters:
    otlp:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}

    otlphttp/outside:
      endpoint: http://k8s-oteldemo-bbd9607320-1933917927.us-west-2.elb.amazonaws.com:80
      # traces_endpoint: http://k8s-oteldemo-bbd9607320-1933917927.us-west-2.elb.amazonaws.com:80/v1/traces
      tls:
        insecure: true

    otlp/metrics:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-metrics

    otlp/logging:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-logs

  service:
    telemetry:
      logs:
        level: "debug"
    pipelines:
      traces:
        receivers: [otlp]
        processors: [k8sattributes, transform/labelme, memory_limiter, batch]
        exporters: [otlp, otlphttp/outside]
      metrics:
        receivers: [otlp]
        processors: [k8sattributes, transform/labelme, memory_limiter, batch]
        exporters: [otlp/metrics, otlphttp/outside]
      logs:
        receivers: [otlp]
        processors: [k8sattributes, transform/labelme, memory_limiter, batch]
        exporters: [otlp/logging]
